version: '3'
services:

  envoy:
    build:
      context: ./envoy
      dockerfile: Dockerfile
    volumes:
      - ./envoy/envoy-bootstrap-v3.yml:/etc/envoy.yaml
      - ../target/wasm32-unknown-unknown/release/authfilter.wasm:/etc/authfilter.wasm
    networks:
      envoymesh:
        aliases:
          - provider.front
    expose:
      - "8200"
      - "8201"
    ports:
      - "8200:8200"
      - "8001:8001"

  provider:
    build: ./provider
    networks:
      envoymesh:
        aliases:
          - provider.backend
    expose:
      - "8300"
    ports:
      - "8300:8300"

  consumer:
    build: ./consumer
    networks:
      envoymesh:
        aliases:
          - consumer.service
    expose:
      - "8100"
    ports:
      - "8100:8100"

networks:
  envoymesh: {}