version: '3'
services:

  envoy:
    build:
      context: ./envoy
      dockerfile: Dockerfile
    volumes:
      - ./envoy/envoy-bootstrap-v3.yml:/etc/envoy.yaml
      - ../target/wasm32-unknown-unknown/release/authfilter.wasm:/etc/authfilter.wasm
    networks:
      envoymesh:
        aliases:
          - provider.front
    expose:
      - "8200"
      - "8201"
    ports:
      - "8200:8200"
      - "8001:8001"

  provider:
    build: ./provider
    networks:
      envoymesh:
        aliases:
          - provider.backend
    environment: 
      CONSUMER_PUBLIC_KEY: "-----BEGIN PUBLIC KEY-----

MCowBQYDK2VwAyEAZ4i38pPSEDFvImco80em51Ybp1qM9j0EhLt60AF/ucM=

-----END PUBLIC KEY-----
  
"
    expose:
      - "8300"
    ports:
      - "8300:8300"

  consumer:
    build: ./consumer
    networks:
      envoymesh:
        aliases:
          - consumer.service
    environment:
      CONSUMER_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----

MC4CAQAwBQYDK2VwBCIEIC5tlWucAf9Mqn0G7lXW3L9MTW7GTaMZIH/rlHuIQ51E

-----END PRIVATE KEY-----
  
"
    expose:
      - "8100"
    ports:
      - "8100:8100"

networks:
  envoymesh: {}