version: '3'
services:

  envoy:
    build:
      context: ./envoy
      dockerfile: Dockerfile
    volumes:
      - ./envoy/envoy-bootstrap-v2.yml:/etc/envoy.yaml
      - ../target/wasm32-unknown-unknown/release/authfilter.wasm:/etc/authfilter.wasm
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "18000:80"
      - "18001:8001"

  web_service:
    image: hashicorp/http-echo
    command:
      - '-text="Check response headers for a message from macp"'
    networks:
      envoymesh:
        aliases:
          - web_service
    expose:
      - "5678"
    ports:
      - "18080:5678"

networks:
  envoymesh: {}